[
  { "id": "machine-1",
    "key": {"name": "mac-osx", "version": "10.5.6"},
    "properties": {
      "installed": true
    },
    "config_port": {
      "cpu_arch": "x86",
      "hostname": "jfischer.local",
      "os_user_name": "jfischer"
    },
    "output_ports": {
      "host": {
        "cpu_arch": "x86",
        "hostname": "jfischer.local",
        "os_type": "mac-osx",
        "os_user_name": "jfischer"
      }
    }
  },
  { "id": "jdk-1",
    "key": {"name": "java-developer-kit", "version": "1.5"},
    "properties": {
      "installed": true
    },
    "config_port": {
      "JAVA_HOME": "/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home"
    },
    "input_ports": {
      "host": {
        "cpu_arch": "x86",
        "hostname": "jfischer.local",
        "os_type": "mac-osx",
        "os_user_name": "jfischer"
      }
    },
    "output_ports": {
      "jdk": {
        "home": "/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home",
        "type": "jdk"
      }
    },
    "inside": {
      "id": "machine-1",
      "key": {"name": "mac-osx", "version": "10.5.6"},
      "port_mapping": {
        "host": "host"
      }
    }
  },
  { "id": "mysql-1",
    "key": {"name": "mysql", "version": "5.1.31"},
    "config_port": {
      "admin_password": "admin",
      "install_dir": "/Users/jfischer/test/mysql",
      "port": 3306
    },
    "input_ports": {
      "host": {
        "cpu_arch": "x86",
        "hostname": "jfischer.local",
        "os_type": "mac-osx",
        "os_user_name": "jfischer"
      }
    },
    "output_ports": {
      "mysql": {
        "host": "jfischer.local",
        "port": 3306
      },
      "mysql_admin": {
        "install_dir": "/Users/jfischer/test/mysql",
        "root_password": "admin"
      }
    },
    "inside": {
      "id": "machine-1",
      "key": {"name": "mac-osx", "version": "10.5.6"},
      "port_mapping": {
        "host": "host"
      }
    }
  },
  { "id": "tomcat-1",
    "key": {"name": "apache-tomcat", "version": "6.0.18"},
    "config_port": {
      "admin_password": "admin",
      "admin_user": "admin",
      "home": "/Users/jfischer/test/tomcat",
      "manager_port": 8080
    },
    "input_ports": {
      "host": {
        "cpu_arch": "x86",
        "hostname": "jfischer.local",
        "os_type": "mac-osx",
        "os_user_name": "jfischer"
      },
      "java": {
        "home": "/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home",
        "type": "jdk"
      }
    },
    "output_ports": {
      "tomcat": {
        "admin_password": "admin",
        "admin_user": "admin",
        "environment_vars": [
          {
            "name": "OPENMRS_RUNTIME_PROPERTIES_FILE",
            "value": "/Users/jfischer/test/openmrs/runtime.properties"
          }
        ],
        "home": "/Users/jfischer/test/tomcat",
        "hostname": "jfischer.local",
        "manager_port": 8080
      }
    },
    "inside": {
      "id": "machine-1",
      "key": {"name": "mac-osx", "version": "10.5.6"},
      "port_mapping": {
        "host": "host"
      }
    },
    "environment": [
      {
        "id": "jdk-1",
        "key": {"name": "java-developer-kit", "version": "1.5"},
        "port_mapping": {
          "java": "jdk"
        }
      }
    ]
  },
  { "id": "openmrs-1",
    "key": {"name": "OpenMRS", "version": "1.3.4"},
    "config_port": {
      "database_password": "openmrs",
      "database_user": "openmrs",
      "home": "/Users/jfischer/test/openmrs"
    },
    "input_ports": {
      "java": {
        "home": "/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home",
        "type": "jdk"
      },
      "mysql": {
        "host": "jfischer.local",
        "port": 3306
      },
      "mysql_admin": {
        "install_dir": "/Users/jfischer/test/mysql",
        "root_password": "admin"
      },
      "tomcat": {
        "admin_password": "admin",
        "admin_user": "admin",
        "environment_vars": [
          {
            "name": "OPENMRS_RUNTIME_PROPERTIES_FILE",
            "value": "/Users/jfischer/test/openmrs/runtime.properties"
          }
        ],
        "home": "/Users/jfischer/test/tomcat",
        "hostname": "jfischer.local",
        "manager_port": 8080
      }
    },
    "output_ports": {
      "openmrs": {
        "url": "jfischer.local:8080/openmrs"
      }
    },
    "inside": {
      "id": "tomcat-1",
      "key": {"name": "apache-tomcat", "version": "6.0.18"},
      "port_mapping": {
        "tomcat": "tomcat"
      }
    },
    "environment": [
      {
        "id": "jdk-1",
        "key": {"name": "java-developer-kit", "version": "1.5"},
        "port_mapping": {
          "java": "jdk"
        }
      }
    ],
    "peers": [
      {
        "id": "mysql-1",
        "key": {"name": "mysql", "version": "5.1.31"},
        "port_mapping": {
          "mysql": "mysql",
          "mysql_admin": "mysql_admin"
        }
      }
    ]
  }
]
